# 목록 G.25 Alexa skill: serverless.yml

service: aws-python-alexa-skill

provider:
  name: aws
  runtime: python2.7

functions:
  luckyNumber:
    handler: handler.lucky_number
    events:
      - alexaSkill
